In [10]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from matplotlib import pylab
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas import *
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [11]:
import numpy as np
import pandas as pd

df = pd.read_csv('spam_ham.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [12]:
X = df['Message']
y = df['Category']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [14]:
tfidf = TfidfVectorizer()

In [16]:
tfidf_x_train=tfidf.fit_transform(X)

In [17]:
tfidf_x_train

<5572x8709 sparse matrix of type '<class 'numpy.float64'>'
	with 74098 stored elements in Compressed Sparse Row format>

In [18]:
print(tfidf_x_train)

  (0, 8320)	0.1824010162830269
  (0, 1079)	0.32645117023873077
  (0, 3611)	0.15304155020494284
  (0, 7690)	0.15550627816331294
  (0, 2057)	0.2757872678027423
  (0, 1761)	0.31163292870610654
  (0, 4497)	0.2757872678027423
  (0, 8544)	0.2208188335194995
  (0, 3651)	0.18033180630708256
  (0, 1763)	0.2757872678027423
  (0, 4110)	0.10707657674366397
  (0, 5567)	0.15636623031957597
  (0, 1313)	0.24417482890859651
  (0, 2334)	0.25281395947472957
  (0, 5954)	0.25533539230157154
  (0, 4370)	0.32645117023873077
  (0, 8080)	0.23000344108357726
  (0, 3567)	0.1478647506898016
  (1, 5563)	0.5466243141314314
  (1, 8446)	0.43162957585464123
  (1, 4338)	0.5236804332035243
  (1, 4533)	0.4083258549263009
  (1, 5534)	0.2718944069420321
  (2, 77)	0.23031755640837923
  (2, 1166)	0.1655500619657908
  :	:
  (5570, 1798)	0.28297500390378505
  (5570, 3485)	0.27533078711486225
  (5570, 2901)	0.24405689679889953
  (5570, 7095)	0.20538337055860154
  (5570, 1790)	0.13631002689236146
  (5570, 8116)	0.208848789326782

In [19]:
X = tfidf_x_train.toarray()
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
dd = pd.DataFrame(data = X)
dd

0     1     2     3     4     5     6     7     8     9     ...  8699  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
5567   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
5568   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
5569   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
5570   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
5571   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      8700  8701  8702  8703  8704  8705  8706  8707  8708  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
5567   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5568   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5569   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5570   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5571   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5572 rows x 8709 columns]

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [59]:
model = MultinomialNB().fit(X_train,y_train)

In [61]:
prediction = model.predict(X_test)
print(prediction)

['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']


In [62]:
from sklearn.metrics import accuracy_score

accuracy_score(prediction,y_test)

0.9569377990430622

In [63]:
y_test  #actual records of y_test

4456     ham
690     spam
944      ham
3768     ham
1189     ham
        ... 
4833     ham
3006     ham
509      ham
1761     ham
1525     ham
Name: Category, Length: 1672, dtype: object